"""
Django settings for TrinityEd_project project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-5)lm(y#pn_eom0$qitb7izww#cn96e)w0zdw*zytifue_v=7f#'

DEBUG = True
ALLOWED_HOSTS = ['trinityed.onrender.com']

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TrinityEd_app',
    'accounts'
]

JAZZMIN_SETTINGS = {
    # Basic info
    "site_title": "TrinityEd Dashboard",
    "site_header": "TrinityEd Admin",
    "site_brand": "TrinityEd",
    "welcome_sign": "Empowering Student Success!",
    "copyright": "TrinityEd © 2025",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "TrinityEd_app", "accounts"],
    "topmenu_links": [
        {"name": "Home",  "url": "home", "permissions": ["auth.view_user"]},
        {"name": "Documentation", "url": "https://trinityed.com/docs/", "new_window": True},
    ],

    # UI options
    "changeform_format": "horizontal_tabs",  # horizontal_tabs / stacked / collapsible
    "changeform_format_overrides": {"auth.user": "collapsible"},
    "list_per_page": 25,
    "show_ui_builder": True,
    "related_modal_active": True,
    
    # Styling options
    # "site_logo": "images/logo.png",  # ❌ Remove this line
    # "site_logo_classes": "img-circle shadow-lg",  # ❌ Remove this line
    "site_icon": "fas fa-graduation-cap",
    
    # Colors and theme
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "custom_css": "css/custom_jazzmin.css",  
    "custom_js": "js/custom_jazzmin.js",
    
    # Sidebar & menu icons
    "icons": {
        "auth": "fas fa-users-cog",
        "TrinityEd_app.student": "fas fa-user-graduate",
        "TrinityEd_app.attendance": "fas fa-calendar-check",
        "TrinityEd_app.performance": "fas fa-chart-line",
        "TrinityEd_app.alert": "fas fa-bell",
    },
    
    # UI tweaks
    "show_ui_builder": True,
    "show_sidebar_icons": True,
}


# Custom user model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TrinityEd_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TrinityEd_project.wsgi.application'   # ✅ Fixed


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# # REST F# The `REST_FRAMEWORK` settings in Django are used to configure the behavior of the Django
# REST framework, which is a powerful and flexible toolkit for building Web APIs.
# framework settings
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }



# EMAIL Auth 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "godanishubham30@gmail.com"
EMAIL_HOST_PASSWORD = "cjiu mtga qdmd elna"  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 10


# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For testing
# Or use a real email backend like SMTP
# DEFAULT_FROM_EMAIL = 'godanishubham30@gmail.com'
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Get Gemini key from environment
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("⚠️ GEMINI_API_KEY is not set! Please check your .env file.")
