# Generated by Django 5.2.6 on 2025-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(blank=True, help_text='Enrollment number for students (optional for non-students).', max_length=20, null=True, unique=True),
        ),
    ]
