# Generated by Django 5.2.3 on 2025-09-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250916_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
    ]
