# Generated by Django 5.2.3 on 2025-09-16 08:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('attendance_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('average_score', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(10.0)])),
                ('is_at_risk', models.BooleanField(default=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('enrollment_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('course', models.CharField(default='Default Course', max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('credits_earned', models.IntegerField(default=0)),
                ('total_credits', models.IntegerField(default=0)),
                ('incidents_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_labels', models.JSONField(blank=True, default=list, help_text="Labels for GPA trend (e.g., ['Jan 01', 'Jan 15'])")),
                ('gpa_data', models.JSONField(blank=True, default=list, help_text='GPA data points (e.g., [75, 80])')),
                ('attendance_labels', models.JSONField(blank=True, default=list, help_text="Labels for attendance trend (e.g., ['Jan 2025'])")),
                ('attendance_data', models.JSONField(blank=True, default=list, help_text='Attendance percentage data (e.g., [95, 90])')),
                ('subject_labels', models.JSONField(blank=True, default=list, help_text="Subject names (e.g., ['Math', 'Science'])")),
                ('subject_data', models.JSONField(blank=True, default=list, help_text='Average scores per subject (e.g., [85, 78])')),
                ('grade_summary', models.JSONField(blank=True, default=list, help_text="Summary of grades (e.g., [{'subject': 'Math', 'grade': 'A'}])")),
                ('incidents_count', models.PositiveIntegerField(default=0, help_text='Total number of incidents')),
                ('incident_list', models.JSONField(blank=True, default=list, help_text="List of incident descriptions (e.g., ['Incident 1'])")),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the progress data was updated')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_data', to='TrinityEd_app.student')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Students Progress',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage', models.FloatField(default=0.0)),
                ('test_date', models.DateField(default=datetime.date.today)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='TrinityEd_app.student')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrinityEd_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's name", max_length=100)),
                ('email', models.EmailField(help_text="Student's email", max_length=254)),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled session time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mentor', models.ForeignKey(blank=True, help_text='Selected mentor', limit_choices_to={'is_mentor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='TrinityEd_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('percentage', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrinityEd_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('icon', models.CharField(default='notifications', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='TrinityEd_app.student')),
            ],
        ),
    ]
