# Generated by Django 5.2.3 on 2025-09-16 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellingsession',
            options={'verbose_name': 'Counselling Session', 'verbose_name_plural': 'Counselling Sessions'},
        ),
        migrations.AddField(
            model_name='counsellingsession',
            name='description',
            field=models.TextField(blank=True, help_text='Concern description', null=True),
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='mentor',
            field=models.ForeignKey(blank=True, help_text='Selected mentor', limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
