# Generated by Django 5.2.6 on 2025-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0002_student_performance_fee_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_no', models.CharField(max_length=50, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('performance_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
