# Generated by Django 5.2.6 on 2025-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0003_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='total_fee',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
