# Generated by Django 5.2.6 on 2025-09-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0004_alter_fee_total_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='name',
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='learner',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='enrollment_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
