# Generated by Django 5.2.3 on 2025-09-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0004_alter_counsellingsession_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounsellingSession',
        ),
    ]
