# Generated by Django 5.2.3 on 2025-09-16 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0005_delete_counsellingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's name", max_length=100)),
                ('email', models.EmailField(help_text="Student's email", max_length=254)),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled session time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional session details', null=True)),
                ('mentor', models.ForeignKey(blank=True, help_text='Selected mentor', limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='TrinityEd_app.student')),
            ],
        ),
    ]
