# Generated by Django 5.2.6 on 2025-09-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0005_remove_learner_email_remove_learner_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
