# Generated by Django 5.2.6 on 2025-09-15 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0006_delete_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='recorded_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='week',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrinityEd_app.student'),
        ),
    ]
