# Generated by Django 5.2.6 on 2025-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0006_counsellingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='area_of_interest',
            field=models.TextField(blank=True, help_text="Student's academic/career interests", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dropout',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Is the student planning to drop out?', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='need_counselling',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Does the student need counselling?', max_length=10),
        ),
    ]
