# Generated by Django 5.2.6 on 2025-09-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0007_student_area_of_interest_student_dropout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dropout',
        ),
    ]
