# Generated by Django 5.2.6 on 2025-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0007_remove_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
