# Generated by Django 5.2.6 on 2025-09-25 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0008_remove_student_dropout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={},
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellingsession',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='attendance_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='attendance_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='gpa_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='gpa_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='grade_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='incident_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='incidents_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
