# Generated by Django 5.2.6 on 2025-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrinityEd_app', '0008_attendance_percentage_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='subject',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
